const demos = [
  {
    name: 'Events',
    screenshot: 'img/screenshots/events.png',
    link: '/events.html',
    new: false,
  },
  {
    name: 'Events v2',
    screenshot: 'img/screenshots/events-2.png',
    link: '/events-2.html',
    new: false,
  },
  {
    name: 'How to',
    screenshot: 'img/screenshots/how.png',
    link: '/how.html',
    new: false,
  },
  {
    name: 'Home v1',
    screenshot: 'img/screenshots/home-1.png',
    link: '/home-1.html',
    new: false,
  },
  {
    name: 'Home v5',
    screenshot: 'img/screenshots/home-5.png',
    link: '/home-5.html',
    new: false,
  },
  {
    name: 'Home v6',
    screenshot: 'img/screenshots/home-6.png',
    link: '/home-6.html',
    new: false,
  },
  {
    name: 'Home v2',
    screenshot: 'img/screenshots/home-2.png',
    link: '/home-2.html',
    new: false,
  },
  {
    name: 'Home v3',
    screenshot: 'img/screenshots/home-3.png',
    link: '/home-3.html',
    new: false,
  },
  {
    name: 'Home v4',
    screenshot: 'img/screenshots/home-4.png',
    link: '/home-4.html',
    new: false,
  },
  {
    name: 'Trips',
    screenshot: 'img/screenshots/trips.png',
    link: '/trips.html',
    new: false,
  },
  {
    name: 'Home',
    screenshot: 'img/screenshots/trips.png',
    link: '/home.html',
    new: false,
  },
  {
    name: 'Trips v2',
    screenshot: 'img/screenshots/trips-2.png',
    link: '/trips-2.html',
    new: false,
  },
  {
    name: 'Trips v3',
    screenshot: 'img/screenshots/trips-3.png',
    link: '/trips-3.html',
    new: false,
  },
  {
    name: 'Flats',
    screenshot: 'img/screenshots/flats.png',
    link: '/flats.html',
    new: false,
  },
  {
    name: 'Listing',
    screenshot: 'img/screenshots/flats.png',
    link: '/listing.html',
    new: false,
  },
  {
    name: 'Event v1',
    screenshot: 'img/screenshots/event.png',
    link: '/event.html',
    new: false,
  },
  {
    name: 'Event v2',
    screenshot: 'img/screenshots/event-2.png',
    link: '/event-2.html',
    new: false,
  },
  {
    name: 'Event v3',
    screenshot: 'img/screenshots/event-3.png',
    link: '/event-3.html',
    new: false,
  },
  {
    name: 'Event v4',
    screenshot: 'img/screenshots/event-4.png',
    link: '/event-4.html',
    new: false,
  },
  {
    name: 'Event v5',
    screenshot: 'img/screenshots/event-5.png',
    link: '/event-5.html',
    new: false,
  },
  {
    name: 'Flat v1',
    screenshot: 'img/screenshots/flat.png',
    link: '/flat.html',
    new: false,
  },
  {
    name: 'Flat v2',
    screenshot: 'img/screenshots/flat-2.png',
    link: '/flat-2.html',
    new: false,
  },
  {
    name: 'Flat v3',
    screenshot: 'img/screenshots/flat-3.png',
    link: '/flat-3.html',
    new: false,
  },
  {
    name: 'Flat v4',
    screenshot: 'img/screenshots/flat-4.png',
    link: '/flat-4.html',
    new: false,
  },
  {
    name: 'Flat v5',
    screenshot: 'img/screenshots/flat-5.png',
    link: '/flat-5.html',
    new: false,
  },
  {
    name: 'Trip v1',
    screenshot: 'img/screenshots/trip.png',
    link: '/trip.html',
    new: false,
  },
  {
    name: 'Trip v2',
    screenshot: 'img/screenshots/trip-2.png',
    link: '/trip-2.html',
    new: false,
  },
  {
    name: 'Trip v3',
    screenshot: 'img/screenshots/trip-3.png',
    link: '/trip-3.html',
    new: false,
  },
  {
    name: 'Trip v4',
    screenshot: 'img/screenshots/trip-4.png',
    link: '/trip-4.html',
    new: false,
  },
  {
    name: 'Trip v5',
    screenshot: 'img/screenshots/trip-5.png',
    link: '/trip-5.html',
    new: false,
  },
  {
    name: 'Pricing',
    screenshot: 'img/screenshots/pricing.png',
    link: '/pricing.html',
    new: false,
  },
  {
    name: 'Corporate',
    screenshot: 'img/screenshots/corporate.png',
    link: '/corporate.html',
    new: false,
  },
  {
    name: 'Support',
    screenshot: 'img/screenshots/support.png',
    link: '/support.html',
    new: false,
  },
  {
    name: 'Host',
    screenshot: 'img/screenshots/host.png',
    link: '/host.html',
    new: false,
  },
  {
    name: 'Careers',
    screenshot: 'img/screenshots/careers.png',
    link: '/careers.html',
    new: false,
  },
  {
    name: 'Careers v2',
    screenshot: 'img/screenshots/careers-2.png',
    link: '/careers-2.html',
    new: false,
  },
  {
    name: 'Help Center',
    screenshot: 'img/screenshots/help-center.png',
    link: '/help-center.html',
    new: false,
  },
  {
    name: 'Blog',
    screenshot: 'img/screenshots/blog.png',
    link: '/blog.html',
    new: false,
  },
  {
    name: 'Post',
    screenshot: 'img/screenshots/post.png',
    link: '/post.html',
    new: false,
  },
  {
    name: 'Account',
    screenshot: 'img/screenshots/account-main.png',
    link: '/account-main.html',
    new: false,
  },
  {
    name: 'Account Layout',
    screenshot: 'img/screenshots/account-personal.png',
    link: '/account-personal.html',
    new: false,
  },
  {
    name: 'Schedule',
    screenshot: 'img/screenshots/account-schedule.png',
    link: '/account-schedule.html',
    new: false,
  },
  {
    name: 'Contact',
    screenshot: 'img/screenshots/contact.png',
    link: '/contact.html',
    new: false,
  },
  {
    name: 'Login',
    screenshot: 'img/screenshots/login.png',
    link: '/login.html',
    new: false,
  },
  {
    name: 'Signup',
    screenshot: 'img/screenshots/signup.png',
    link: '/signup.html',
    new: false,
  },
  {
    name: 'Signup v2',
    screenshot: 'img/screenshots/signup-2.png',
    link: '/signup-2.html',
    new: false,
  },
  {
    name: 'Error 404',
    screenshot: 'img/screenshots/error-1.png',
    link: '/error-1.html',
    new: false,
  },
  {
    name: 'Terms Of Service',
    screenshot: 'img/screenshots/terms.png',
    link: '/terms.html',
    new: false,
  },

  {
    name: 'Details',
    screenshot: 'img/screenshots/flat.png',
    link: '/details.html',
    new: false,
  },
]


export function initRenderDemos(){
  return {
    screenshots: demos
  }
}